CC = gcc
CFLAGS = -Wall

CLIENT_SOURCE_DIR = client
CLIENT_SOURCES = $(CLIENT_SOURCE_DIR)/client2.c
CLIENT_OUTPUT = client

SERVER_SOURCE_DIR = server
SERVER_SOURCES = $(SERVER_SOURCE_DIR)/awale.c $(SERVER_SOURCE_DIR)/server2.c
SERVER_OUTPUT = server

all: client server

client: $(CLIENT_SOURCES)
	$(CC) $(CFLAGS) $(CLIENT_SOURCES) -o $(CLIENT_SOURCE_DIR)/$(CLIENT_OUTPUT)

server: $(SERVER_SOURCES)
	$(CC) $(CFLAGS) $(SERVER_SOURCES) -o $(SERVER_SOURCE_DIR)/$(SERVER_OUTPUT)

clean:
	rm -f $(SERVER_SOURCE_DIR)/$(SERVER_OUTPUT) $(CLIENT_SOURCE_DIR)/$(CLIENT_OUTPUT)
